#!/bin/bash
set -e

function get_ruby {
	if ! command -v ruby >/dev/null 2>&1; then
		echo "Installing Ruby..."

		apt-get update

		apt-get -y install python-software-properties
		apt-add-repository ppa:brightbox/ruby-ng-experimental

		apt-get update


		ruby-switch --set ruby1.9.1
	fi
}

get_ruby
